### ISSUE TITLE
Move webpack to local devdependencies

### ISSUE THREAD

**Issue by Qquanwei** [yosbelms/ramdascript-todomvc#1]
extra package and script, this will be helpful with install & start
```
devdependencies:
  webpack
  npx

scripts:
  start: npx webpack
```

**Comment by yosbelms** [comment]
Since this project is just a RamdaScript showcase I prefer to keep tooling simple. So, I skipped `npx` for now. Webpack is added to `devDependencies` 9817789fcd498770aa0294f391b7a6fe5189212e, the `build`  command is added in d18132677a3db2f25f3b660f78cca8c5d891e1b9

**Comment by Qquanwei** [comment]
great!
